<?php

namespace math\MathCaptcha;
/**
 * Created by PhpStorm.
 * User: dudj
 * Date: 12.03.2019
 * Time: 14:24
 */
class MathCaptchaAction extends \yii\captcha\CaptchaAction
{
    public $minLength = 0;
    public $maxLength = 100;

    private $_lineCount;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->_lineCount = rand(3, 5);
    }

    /**
     * @inheritdoc
     */
    protected function generateVerifyCode()
    {
        return mt_rand((int)$this->minLength, (int)$this->maxLength);
    }

    /**
     * @inheritdoc
     */
    protected function renderImage($code)
    {
        return parent::renderImage($this->getText($code));
    }

    protected function getText($code)
    {
        $code = (int)$code;
        $rand = mt_rand(min(1, $code - 1), max(1, $code - 1));
        $operation = mt_rand(0, 1);
        if ($operation === 1) {
            return $code - $rand . '+' . $rand;
        } else {
            return $code + $rand . '-' . $rand;
        }
    }

    /**
     * Renders the CAPTCHA image based on the code using GD library.
     * @param string $code the verification code
     * @return string image contents in PNG format.
     */
    protected function renderImageByGD($code)
    {
        $image = imagecreatetruecolor($this->width, $this->height);
        //创建画布背景句柄
        $color = imagecolorallocate($image,rand(0, 150), rand(0, 100), rand(0, 120));
        //填充背景颜色
        imagefill($image,0,0,$color);

//        $backColor = imagecolorallocate($image, rand(0, 150), rand(0, 100), rand(0, 120));
//        imagefilledrectangle($image, 0, 0, $this->width - 1, $this->height - 1, $backColor);
//        imagecolordeallocate($image, $backColor);


        //使用imageline函数给画布添加干扰线
        for ($i=0; $i<$this->_lineCount; $i++)
        {
            $color = imagecolorallocate($image, rand(0, 255), rand(0, 255), rand(0, 255));
            imageline($image, rand(0, 20), rand(1, 50), rand(150, 180), rand(1, 50), $color);
        }
        $codeArr = [];
        $j=0;
        for($i=0;$i<strlen($code);$i++){
            if(in_array($code[$i],['+','-','*','/'])){
                $j++;
                $codeArr[$j] = $code[$i];
                $j++;
            }else{
                $val = isset($codeArr[$j])?$codeArr[$j]:'';
                $codeArr[$j] = $val.$code[$i];
            }
        }
        $length = count($codeArr);
        $box = imagettfbbox(30, 0, $this->fontFile, $code);
        $w = $box[4] - $box[0] + $this->offset * ($length - 1);
        $h = $box[1] - $box[5];
        $scale = min(($this->width - $this->padding * 2) / $w, ($this->height - $this->padding * 2) / $h);
        $x = 10;
        $y = round($this->height * 12 / 40);

        for ($i = 1; $i <= $length; ++$i) {
            $strcolor = imagecolorallocate($image, rand(0, 255), rand(0, 255), rand(50, 255));;
            $fontSize = (int) (rand(24, 32) * $scale);
            imagestring($image, $fontSize, 25*$i, $y, $codeArr[$i-1], $strcolor);
//            $angle = rand(-20, 20);
//            $letter = $code[$i];
//            $box = imagettftext($image, $fontSize, $angle, $x, $y, $foreColor, $this->fontFile, $letter);
//            $x = $box[2] + $this->offset;
        }
        //使用imagesetpixel函数给画布添加干扰点
        for($i=1;$i<=200*100*0.01;$i++){
            $fillcolor=imagecolorallocate($image,mt_rand(0,200),mt_rand(0,200),mt_rand(0,255));
            imagesetpixel($image,mt_rand(0,199),mt_rand(0,49),$fillcolor);
        }

        ob_start();
        imagepng($image);
        imagedestroy($image);

        return ob_get_clean();
    }

    /**
     * Renders the CAPTCHA image based on the code using ImageMagick library.
     * @param string $code the verification code
     * @return string image contents in PNG format.
     */
    protected function renderImageByImagick($code)
    {
        //$backColor = $this->transparent ? new \ImagickPixel('transparent') : new \ImagickPixel('#' . str_pad(dechex($this->backColor), 6, 0, STR_PAD_LEFT));
        $backColor = new \ImagickPixel(sprintf('rgb(%d,%d,%d)',rand(0, 255), rand(0, 255), rand(0, 255)));

        $image = new \Imagick();
        $image->newImage($this->width, $this->height, $backColor);

        $draw = new \ImagickDraw();

        for ($i=0; $i<$this->_lineCount; $i++)
        {
            $color =  new \ImagickPixel(sprintf('rgb(%d,%d,%d)',rand(0, 255), rand(0, 255), rand(0, 255)));
            $draw->setStrokeColor($color);
            $draw->line(rand(0, 20), rand(1, 50), rand(150, 180), rand(1, 50));
        }

        $draw->setFont($this->fontFile);
        $draw->setFontSize(30);
        $fontMetrics = $image->queryFontMetrics($draw, $code);

        $length = strlen($code);
        $w = (int) $fontMetrics['textWidth'] - 8 + $this->offset * ($length - 1);
        $h = (int) $fontMetrics['textHeight'] - 8;
        $scale = min(($this->width - $this->padding * 2) / $w, ($this->height - $this->padding * 2) / $h);
        $x = 10;
        $y = round($this->height * 27 / 40);
        for ($i = 0; $i < $length; ++$i) {
            $foreColor = new \ImagickPixel(sprintf('rgb(%d,%d,%d)',rand(0, 255), rand(0, 255), rand(0, 255)));
            $draw = new \ImagickDraw();
            $draw->setFont($this->fontFile);
            $draw->setFontSize((int) (rand(24, 32) * $scale * 0.8));
            $draw->setFillColor($foreColor);
            $image->annotateImage($draw, $x, $y, rand(-20, 20), $code[$i]);
            $fontMetrics = $image->queryFontMetrics($draw, $code[$i]);
            $x += (int) $fontMetrics['textWidth'] + $this->offset;
        }

        for ($i=0; $i<$this->_lineCount; $i++)
        {
            $color =  new \ImagickPixel(sprintf('rgb(%d,%d,%d)',rand(0, 255), rand(0, 255), rand(0, 255)));
            $draw->setStrokeColor($color);
            $draw->line(rand(0, 20), rand(1, 50), rand(150, 180), rand(1, 50));
        }

        $image->drawImage( $draw );

        $image->setImageFormat('png');
        return $image->getImageBlob();
    }
}